version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.0-browsers
    working_directory: ~/repo
    environment:
      NODE_ENV: test

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - deploy:
          command: |
            bash ./.circleci/add-ssh-hosts.sh
            echo "Current branch ${CIRCLE_BRANCH}"
            if [ "${CIRCLE_BRANCH}" == "development" ] || [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Start deploy"
              git remote -v
              bash ./.circleci/install-packages.sh
              bash ./.circleci/deploy-heroku.sh $CIRCLE_BRANCH
            fi
